#RSTForum:- simple IOS config in ansible
---
- name: RSTForum- Config for Ansible
  hosts: IOS
  gather_facts: no

  tasks:

  - name: RSTForum- Create loopback 10
    ios_interface:
      name: Loopback10
      enabled: True
      description: RSTForum ansible script created interface 
  - name: RSTForum- Assign IP to loopback
    ios_l3_interface:
      name: Loopback10
      ipv4: 100.100.100.100/32


