#simple IOS config in ansible
---
- name: RSTForum- Sample IOS show ntp for Ansible 2.5
  hosts: IOS
  gather_facts: no

  tasks:

  - name: RSTForum- Run show ntp associations
    ios_command:
      commands: show ntp associations
    register: RSTForum_ntp

  - name: RSTForum- Display value of "RSTForum_ntp" variable
    debug:
      var: RSTForum_ntp["stdout_lines"][0]


