#RSTForum- config in ansible
---
- name: RSTForum- Cleanup config for Ansible
  hosts: IOS
  gather_facts: no

  tasks:

  - name: RSTForum- Delete ntp server 100.100.100.200 via CLI
    ios_config:
      lines:
        - no ntp server 100.100.100.100
    ignore_errors: True
    failed_when: false

  - name: RSTForum- Delete loopback 10
    ios_interface:
      name: Loopback10
      state: absent
    ignore_errors: True
    failed_when: false



